import { SalesData, ProductItem, TeamMember, CategoryData } from '@/types';

export const salesData: SalesData[] = [
  { month: 'Jan', sales: 45000, insight: 35000 },
  { month: 'Feb', sales: 52000, insight: 42000 },
  { month: 'Mar', sales: 48000, insight: 38000 },
  { month: 'Apr', sales: 61000, insight: 51000 },
  { month: 'May', sales: 70901, insight: 60000 },
  { month: 'Jun', sales: 92921, insight: 75000 },
  { month: 'Jul', sales: 58000, insight: 48000 },
  { month: 'Aug', sales: 65000, insight: 55000 },
  { month: 'Sep', sales: 71000, insight: 61000 },
  { month: 'Oct', sales: 68000, insight: 58000 },
  { month: 'Nov', sales: 75000, insight: 65000 },
  { month: 'Dec', sales: 82000, insight: 72000 },
];

export const products: ProductItem[] = [
  {
    id: '1',
    name: 'Etro Leather Jacket',
    type: 'Jacket',
    sales: 341,
    stock: 23,
    price: 521,
    status: 'in-stock',
  },
  {
    id: '2',
    name: 'Owens Black Pants',
    type: 'Pants',
    sales: 322,
    stock: 190,
    price: 102,
    status: 'in-stock',
  },
  {
    id: '3',
    name: 'Moncler Wind Jacket',
    type: 'Jacket',
    sales: 320,
    stock: 0,
    price: 490,
    status: 'out-of-stock',
  },
  {
    id: '4',
    name: 'Loeweve Blue Plain',
    type: 'T-shirt',
    sales: 320,
    stock: 52,
    price: 99,
    status: 'in-stock',
  },
  {
    id: '5',
    name: 'FOG Green Short',
    type: 'Pants',
    sales: 318,
    stock: 0,
    price: 92,
    status: 'out-of-stock',
  },
  {
    id: '6',
    name: 'Grogreen Leather Jacket',
    type: 'Jacket',
    sales: 312,
    stock: 21,
    price: 390,
    status: 'in-stock',
  },
  {
    id: '7',
    name: 'Bury Navy Polo Shirt',
    type: 'Polo',
    sales: 308,
    stock: 0,
    price: 120,
    status: 'out-of-stock',
  },
  {
    id: '8',
    name: 'Stone Black Jacket',
    type: 'Jacket',
    sales: 302,
    stock: 31,
    price: 500,
    status: 'in-stock',
  },
  {
    id: '9',
    name: 'Cleverry Shoes',
    type: 'Shoes',
    sales: 300,
    stock: 52,
    price: 360,
    status: 'in-stock',
  },
  {
    id: '10',
    name: 'Glemiss Slop Shoes',
    type: 'Shoes',
    sales: 291,
    stock: 44,
    price: 400,
    status: 'in-stock',
  },
];

export const teamMembers: TeamMember[] = [
  {
    id: '1',
    name: 'Mariana Girgantuti',
    email: 'marianagrgnt7@gmail.com',
    title: 'Leader Design Team',
    taskProgress: 75,
    lastActive: '24/6/2024',
    team: ['Design', 'Product', 'Operations'],
  },
  {
    id: '2',
    name: 'Christ Evandro',
    email: 'evandrocst@gmail.com',
    title: 'Sales Team',
    taskProgress: 90,
    lastActive: '19/6/2024',
    team: ['Sales', 'Operations'],
  },
  {
    id: '3',
    name: 'Martial Vianz',
    email: 'martialv1@gmail.com',
    title: 'Social Media Team',
    taskProgress: 45,
    lastActive: '20/6/2024',
    team: ['Social Media', 'Product'],
  },
  {
    id: '4',
    name: 'Zhikov Martinov',
    email: 'zhikov00@gmail.com',
    title: 'Leader Ads Team',
    taskProgress: 85,
    lastActive: '10/6/2024',
    team: ['Ads', 'Product', 'Operations'],
  },
];

export const categoryData: CategoryData[] = [
  { name: 'Ecommerce', value: 3200, color: '#6366F1' },
  { name: 'Brand Ambassador', value: 2800, color: '#8B5CF6' },
  { name: 'Direct Buy', value: 2214, color: '#06B6D4' },
];